### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by scalpovich** [XEQTIONR/dgl-site#1]
Hi,
Can i get all currents migrations in order to test and perhaps contribute?

**Comment by bytecooled** [comment]
Would it be possible to get migration tables to test?

**Comment by XEQTIONR** [comment]
Hi,

@scalpovich , @bytecooled 

Sorry for being late to reply to this. The migrations are now available on the 'dev' branch. It was previously on the 'migrations' branch. Maybe I didn't initially publish the 'migrations' branch on github, I'm not sure.
